global:
  # 스크랩에 시간을 15s로 설정한다.
  scrape_interval: 15s
  # 내가 원하는 특정 작업을 15s로 설정한다.
  evaluation_interval: 15s

# prometheus가 http로 /metrics를 긁어오는 행위를 말한다.
scrape_configs:
  # target들을 수집 목적/성격 으로 묶은 그룹을 말한다. 
  - job_name: prometheus
    static_configs:
      # 긁어올 주소:포트 한개를 말한다.
      - targets: ["prometheus:9090"]